name: Get upstream updates

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - run: sudo pip install GitPython
      - run: python3 what-changed.py
      - run: cat README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'README: automatic updates'
          branch: 'master'
          file_pattern: 'README.md'
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
