name: Get upstream updates

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  refresh:
    strategy:
      max-parallel: 1
      matrix:
        include:
          - pkgset: 000-test
          - pkgset: 001-pantheon
          - pkgset: 002-maintained
          - pkgset: 003-cinnamon
          - pkgset: 004-xfce
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: sudo pip install GitPython
      - run: python3 src/wc_main.py ${{ matrix.pkgset }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ matrix.pkgset }}: automatic updates"
          file_pattern: "${{ matrix.pkgset }}.md"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
      - run: sleep 10
